DaysCalc/Models/DaysCalc.cs
using DaysCalculator;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DaysCalc.Models
{
    public class DaysCalc
    {
        [Required]
        [Display(Name = "DateFrom")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0: dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public DateFormat DateFrom { get; set; }
        [Required]
        [Display(Name = "DateTo")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0: dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public DateFormat DateTo { get; set; }
    }
}

DaysCalc/Controllers/DaysCalcController.cs
using DaysCalculator;
using System;
using System.Web.Mvc;

namespace DaysCalc.Controllers
{
    public class DaysCalcController : Controller
    {
        // GET: DaysCalc
        public ActionResult Index(FormCollection formCollection)
        {


            //if (DateFrom !=null && DateTo !=null)
            //{
            //    ViewData["NumberofDays"] = CalculateDays(DateFrom, DateTo);
            //}

            ViewData["NumberofDays"] = 0;
            if (formCollection != null && formCollection.Keys.Count > 0)
            {
                DateFormat dt1 = new DateFormat();
                ViewData["NumberofDays"] = 0;

                String datePart = formCollection[0];
                if ((!string.IsNullOrEmpty(formCollection[0])) && (!string.IsNullOrEmpty(formCollection[1])))
                {
                    String[] dateParts = datePart.Split('-');
                    dt1.Year = Convert.ToInt32(dateParts[0]);
                    dt1.month = Convert.ToInt32(dateParts[1]);
                    dt1.days = Convert.ToInt32(dateParts[2]);

                    DateFormat dt2 = new DateFormat();

                    datePart = formCollection[1];
                    dateParts = datePart.Split('-');
                    dt2.Year = Convert.ToInt32(dateParts[0]);
                    dt2.month = Convert.ToInt32(dateParts[1]);
                    dt2.days = Convert.ToInt32(dateParts[2]);

                    ViewData["NumberofDays"] = (dt2 - dt1).days;
                }

            }


            return View();
        }
    }

        
   
}

DaysCalc/Views/DaysCalc/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@model DaysCalc.Models.DaysCalc
<h2>Index</h2>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

@using (Html.BeginForm("Index", "DaysCalc"))
{
    <div>

        <div class="form-group">
            <p>Enter From Date </p>
            @Html.EditorFor(model => model.DateFrom, new { htmlAttributes = new { @class = "form-control date" ,@placeholder = "DD-MM-YYYY" }, required = "required" })

        </div>
        <div class="form-group">
            <p>Enter To Date</p>
            @Html.EditorFor(model => model.DateTo, new { htmlAttributes = new { @class = "form-control date", @format = "DD-MM-YYYY" }, required = "required" })

        </div>

        <div>
            Total Calculated days: @ViewData["NumberofDays"]
        </div>
        <input id="Submit1" type="submit" value="Compare" />
        


    </div>
}

<script src="~/lib/jquery/dist/jquery-3.4.1.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        //alert("ready");
        $('#Submit1').click(function (e) {

            var from = $("#DateFrom").val();
            var to = $("#DateTo").val();

            if (from == 'null' || from =='undefined' || from =='' ) {
                alert("From date Empty");
                e.preventDefault();
                return;
            }
            if (to == 'null' || to == 'undefined' || to == '') {
                alert("To date Empty");
                e.preventDefault();
                return;
            }
            if (Date.parse(from) > Date.parse(to)) {
                alert("From date should be Less than To date");
                e.preventDefault();
                return;
            }

        });
    });


</script>

DaysCalc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Days Calc", "Index", "DaysCalc", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>